### ISSUE TITLE
Stuck setting up Supertokens

### ISSUE THREAD

**Issue by ManuelFFF** [supertokens/supertokens-demo-react#5]
Hi,

I am testing Supertokens in Debian 10. I am new to this kind of apps.

- I am trying the self-hosted setup without docker and with postgresql integration
- Downloaded the corresponding binary file to the server
- Ran `./install`
- App was successfully installed in `/usr/lib/supertokens/`
- Setup postgresql DB, user and password (running local)
- Added credentials to `/usr/lib/supertokens/config.yaml` for the `COMPULSORY` blocks
- Tested connection to DB. OK
- Tested site from browser and got "`Hello`" answer

So far everything seems to be working fine, but what comes next? 

I attempted to setup the frontend, so I downloaded the npm package as described [here](https://supertokens.io/docs/emailpassword/quick-setup/frontend), and after that I got stuck. I can't locate file App.js, so I can't move forward with the rest of the steps. I was hopping to see a sign up/login form like the screenshot in the documentation. 

I downloaded the following via `npm` `supertokens-auth-react`, `supertokens-node` and `supertokens-website`, but I don't know how to integrate those nor use it.

I am not sure if I'm missing something nor what should I do next.

Could you please help me?

Thank you in advance

**Comment by rishabhpoddar** [comment]
Hi @ManuelFFF

At the moment, SuperTokens works with ReactJS frontend and NodeJS backend. Hence, the docs and demo are written with those in mind. So I am assuming that you too are using ReactJS and NodeJS.

In [here](https://supertokens.io/docs/emailpassword/quick-setup/frontend#2-call-the-init-function), the App.js refers to a file created when using the `create-react-app` command to [create a new react app](https://reactjs.org/docs/create-a-new-react-app.html). But if you have made your React app in some other way, you can put the `SuperTokens.init` in any file that contains your root component. 

As per the next steps, you should follow the rest of the tutorial in the frontend setup page from our docs, and then move to the backend setup page. 

If you have any other specific question about implementing SuperTokens, please feel free to repoen this issue or join our [Discord](https://supertokens.io/discord) to ask questions.
